<%@ Page Title="" Language="C#" MasterPageFile="~/Dorknozzle.master" AutoEventWireup="true" CodeBehind="AddressBook.aspx.cs" Inherits="Dorknozzle.AddressBook" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .GridMain
        {}
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHoder1" runat="server">
<h1>Address Book</h1><br />

<asp:LinkButton ID="addEmployee" runat="server" Text="Add New Employee" 
        onclick="addEmployee_Click"></asp:LinkButton>
<asp:GridView ID="grid" runat="server" CssClass="GridMain" CellPadding="4" GridLines="None"
        AutoGenerateColumns="False" DataKeyNames="EmployeeID" 
        DataSourceID="SqlDataSource2" AllowPaging="True" AllowSorting="True" 
        onsorting="grid_Sorting" PageSize="3">
        <RowStyle CssClass="GridRow" />
        <SelectedRowStyle CssClass="GridSelectedRow" />
        <HeaderStyle CssClass="GridHeader" />
        <PagerStyle CssClass="GridRow" />
    <Columns>
        <asp:BoundField DataField="EmployeeID" HeaderText="EmployeeID" 
            InsertVisible="False" ReadOnly="True" />
        <asp:BoundField DataField="Telephone" HeaderText="Telephone" 
            />
        <asp:BoundField DataField="City" HeaderText="City" SortExpression="City" />
        <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
        <asp:CommandField ShowSelectButton="True" />
    </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource2" runat="server" 
        ConnectionString="<%$ ConnectionStrings:Dorknozzle %>" 
        SelectCommand="SELECT * FROM [Employees]"></asp:SqlDataSource>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:Dorknozzle %>" 
        
        SelectCommand="SELECT [EmployeeID], [Name], [Username], [Telephone], [Department], [DepartmentID], [Password], [State], [City] FROM [Employees] WHERE ([EmployeeID] = @EmployeeID)" 
        DeleteCommand="DELETE FROM [Employees] WHERE [EmployeeID] = @EmployeeID" 
        InsertCommand="INSERT INTO [Employees] ([Name], [Username], [Telephone], [Department], [DepartmentID], [Password], [State], [City]) VALUES (@Name, @Username, @Telephone, @Department, @DepartmentID, @Password, @State, @City)" 
        UpdateCommand="UPDATE [Employees] SET [Name] = @Name, [Username] = @Username, [Telephone] = @Telephone, [Department] = @Department, [DepartmentID] = @DepartmentID, [Password] = @Password, [State] = @State, [City] = @City WHERE [EmployeeID] = @EmployeeID">
        <DeleteParameters>
            <asp:Parameter Name="EmployeeID" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="Name" Type="String" />
            <asp:Parameter Name="Username" Type="String" />
            <asp:Parameter Name="Telephone" Type="String" />
            <asp:Parameter Name="Department" Type="String" />
            <asp:Parameter Name="DepartmentID" Type="Int32" />
            <asp:Parameter Name="Password" Type="String" />
            <asp:Parameter Name="State" Type="String" />
            <asp:Parameter Name="City" Type="String" />
        </InsertParameters>
        <SelectParameters>
            <asp:ControlParameter ControlID="grid" Name="EmployeeID" 
                PropertyName="SelectedValue" Type="Int32" />
        </SelectParameters>
        <UpdateParameters>
            <asp:Parameter Name="Name" Type="String" />
            <asp:Parameter Name="Username" Type="String" />
            <asp:Parameter Name="Telephone" Type="String" />
            <asp:Parameter Name="Department" Type="String" />
            <asp:Parameter Name="DepartmentID" Type="Int32" />
            <asp:Parameter Name="Password" Type="String" />
            <asp:Parameter Name="State" Type="String" />
            <asp:Parameter Name="City" Type="String" />
            <asp:Parameter Name="EmployeeID" Type="Int32" />
        </UpdateParameters>
    </asp:SqlDataSource>
    <asp:SqlDataSource ID="SqlDataSource3" runat="server" 
        ConnectionString="<%$ ConnectionStrings:Dorknozzle %>" 
        SelectCommand="SELECT [DepartmentID] AS DepartmentID, [Department] FROM [Departments]">
    </asp:SqlDataSource>
    </h1>
 
    <asp:DetailsView ID="DetailsView1" runat="server" CssClass="GridMain" 
        CellPadding="4" GridLines="None"
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
        AutoGenerateInsertButton="True" AutoGenerateRows="False" 
        DataKeyNames="EmployeeID" DataSourceID="SqlDataSource1" Height="50px" 
        Width="314px" onitemdeleted="DetailsView1_ItemDeleted" 
        oniteminserted="DetailsView1_ItemInserted" 
        onitemupdated="DetailsView1_ItemUpdated">
          <RowStyle CssClass="GridRow" />
      
        <HeaderStyle CssClass="GridHeader" />
        <PagerStyle CssClass="GridRow" />
        <Fields>
            <asp:BoundField DataField="EmployeeID" HeaderText="EmployeeID" 
                InsertVisible="False" ReadOnly="True" SortExpression="EmployeeID" />
            <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
            <asp:BoundField DataField="Username" HeaderText="Username" 
                SortExpression="Username" />
            <asp:BoundField DataField="Telephone" HeaderText="Telephone" 
                SortExpression="Telephone" />
            <asp:BoundField DataField="Department" HeaderText="Department" 
                SortExpression="Department" />
            <asp:TemplateField HeaderText="DepartmentID" SortExpression="DepartmentID">
                <EditItemTemplate>
                    <asp:DropDownList ID="Department" runat="server"
                    DataSourceID="SqlDataSource3" DataTextField="Department" DataValueField="DepartmentID"
                    SelectedValue='<%# Bind("DepartmentID") %>' />
                </EditItemTemplate>
                <InsertItemTemplate>
                     <asp:DropDownList ID="Department" runat="server"
                    DataSourceID="SqlDataSource3" DataTextField="Department" DataValueField="DepartmentID"
                    SelectedValue='<%# Bind("DepartmentID") %>' />
                    </InsertItemTemplate>
                <ItemTemplate>
                    <asp:DropDownList ID="Department" runat="server"
                    DataSourceID="SqlDataSource3" DataTextField="Department" DataValueField="DepartmentID"
                    SelectedValue='<%# Bind("DepartmentID") %>' Enabled="false" />
                </ItemTemplate>
            </asp:TemplateField>
            <asp:BoundField DataField="Password" HeaderText="Password" 
                SortExpression="Password" />
            <asp:BoundField DataField="State" HeaderText="State" SortExpression="State" />
            <asp:BoundField DataField="City" HeaderText="City" SortExpression="City" />
        </Fields>
        <HeaderTemplate>
        <%#Eval ("Name")==null? "Adding New Employee" :Eval("Name") %>
        </HeaderTemplate>
    </asp:DetailsView>

    <br />

    </asp:Content>
